engine: chalkbox.engines.{{ engine }}
---
courseCode: {{ course_code }}
assignment: {{ assignment_id }}
submission: /autograder/submission/
outputFile: /autograder/results/results.json
dependencies: {{ dependencies }}

conformance:
  weighting: {{  }}
  expectedStructure: solutions/correct_structure/
  violationPenalty: {{  }}

functionality:
  weighting: {{  }}
  testDirectory: solutions/correct/test/
  included: {{  }}

junit:
  weighting: {{  }}
  faultySolutions: solutions/faulty/
  assessableTestClasses:
    - tms.intersection.IntersectionTest
    - tms.sensors.DemoPressurePadTest

checkstyle:
  weighting: 15
  config: checkstyle.xml
  jar: lib/checkstyle-8.36-all.jar
  excluded:
    - /autograder/submission/src/tms/display/
  violationPenalty: 0.5
